name: musicbrainz_api
description: Dart implementation of the MusicBrainz API
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^1.2.0
  build_web_compilers: ^2.9.0
dependencies: 
  http: ^0.13.3
  js: ^0.6.3
